ServerPort: 8080 # Port the server will listen on
EnableTLS: true # Enable HTTPS (configure CertPathCrt and CertPathKey if true)
CertPathCrt: "/etc/letsencrypt/live/your-domain.com/fullchain.pem" # Path to the SSL certificate file
CertPathKey: "/etc/letsencrypt/live/your-domain.com/privkey.pem" # Path to the SSL certificate key file
MaxUploadSize: 5368709120 # Maximum upload size limit (Default: 5GB)
MaxExpireHours: 72 # Maximum time (in hours) before the file is deleted (Default: 72h - 3 days)
EnablePassword: true # Enable password authentication for uploads (check credentials.yaml for configuration)
ShowUploadBox: true # Show or hide the 'upload your file' prompt on the download page
UploadDir: "./uploads" # Set uploads dir location
ShowMenuDownloadPage: true # Show Menubar in download page (if true add menu entry for index and upload page)

# Configuration for login attempt rate limiting
RateLimitPeriod: 300    # Time period (in seconds) for rate limiting login attempts (5 minutes)
RateLimitAttempts: 5    # Maximum number of login attempts allowed per IP during the specified period

# Security settings
RequireHTTPS: true      # Redirect HTTP to HTTPS if TLS is enabled
AllowInsecureHTTP: false # Allow HTTP connections when TLS is enabled (not recommended)

# Server timeout settings (in seconds)
ReadTimeout: 600         # Maximum duration for reading the entire request (10 minutes for large uploads)
WriteTimeout: 600        # Maximum duration before timing out writes of the response (10 minutes for large downloads)
IdleTimeout: 120         # Maximum amount of time to wait for the next request when keep-alives are enabled
ReadHeaderTimeout: 30    # Amount of time allowed to read request headers

